### ISSUE TITLE
unresponsive python master_pipeline.py call when error present

### ISSUE THREAD

**Issue by jonnasingh** [orena1/ezfish_pipeline#2]
Calling the pipeline:  python master_pipeline.py --manifest examples/CIM130.hjson

Will just sit there unresponsive if there's an error. The error does not display, instead i have to cancel or CTRL-C out and then the error is displayed. This has happened with 3 error types including:

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nasquatch/data/2p/jonna/EASI_FISH/pipeline/CIM130/OUTPUT/params.hjson'

or

AssertionError: Probe RUNX not supported

So something to report as soon as it runs into any error so that the user doesn't wait for a response that will never come would be useful

**Comment by orena1** [comment]
I think it is something in the terminal itself, try using powershell instead ?

**Comment by jonnasingh** [comment]
will do, currently i solved by fixing all the errors but in the future will use powershell
